services:
  webintel-mcp:
    build: .
    container_name: webintel-mcp
    ports:
      - "3090:3090"
    environment:
      - SEARXNG_HOST=${SEARXNG_HOST:-http://192.168.8.116:8189}
    restart: unless-stopped
