version: '3.8'

services:
  search-app:
    build: .
    container_name: searxng-mcp
    ports:
      - "3090:3090"
    environment:
      - SEARXNG_HOST=http://berry:8189
    restart: unless-stopped
