version: '3.8'

services:
  search-app:
    build: .
    container_name: search-mcp-server
    ports:
      - "3090:3090"
    environment:
      # Configure the SearxNG host via environment variable
      - SEARXNG_HOST=http://berry:8189
    restart: unless-stopped
