services:
  searxng-mcp:
    image: searxng-mcp
    container_name: searxng-mcp
    ports:
      - "3090:3090"
    environment:
      - SEARXNG_HOST=${SEARXNG_HOST:-http://localhost:8189}
    restart: unless-stopped