services:
  searxng-mcp:
    image: ghcr.io/kengbailey/searxng-mcp:latest
    container_name: searxng-mcp
    ports:
      - "3090:3090"
    environment:
      - SEARXNG_HOST=http://localhost:8189
    restart: unless-stopped