services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8189:8080"
    volumes:
      - /home/syran/sandbox/docker/appdata/searxng:/etc/searxng:rw