use_default_settings: true

server:
  bind_address: "0.0.0.0"
  secret_key: "mySECRETkey"  # Generate a random key
  port: 8080

search:
  safe_search: 0
  formats:
    - html
    - json  # Enables programmatic searches

engines:
  - name: google
    engine: google
    shortcut: g

  - name: duckduckgo
    engine: duckduckgo
    shortcut: d

  - name: bing
    engine: bing
    shortcut: b

server.limiter: false